import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Inter via next/font/google — self-hosted, no layout shift. Coinbase Sans (the
// v1 typeface) is not publicly available, so Inter is the locked substitute.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
