"use client";

import { useEffect, useRef } from "react";

import { readHandoff } from "@/lib/handoff";
import type { ScoreData } from "@/lib/api/types";
import { useControls } from "@/lib/hooks/useControls";
import { useScore } from "@/lib/hooks/useScore";
import { scoreToTier } from "@/lib/scoring";
import { useDashboardStore } from "@/lib/stores/dashboardStore";

import { ControlsGrid } from "./ControlsGrid";
import { HeaderActions } from "./HeaderActions";
import { LoadReportDropzone } from "./LoadReportDropzone";
import { ScoreChart } from "./ScoreChart";
import { ScoreSummary } from "./ScoreSummary";

// Module scope (not render): build + download the formatted .txt report, exactly
// like the HTML lama's downloadReport (Agent/Score/Tier/Date + controls table).
function buildReportText(d: ScoreData): string {
  const pct = d.score_pct ?? d.final_score;
  const rows = (d.controls ?? [])
    .map(
      (c) =>
        `  ${String(c.ctrl).padEnd(10)} ${String(c.score).padStart(4)}/${c.max}  ${c.finding ?? ""}`,
    )
    .join("\n");
  return [
    "ACP-SEC Audit Report",
    "====================",
    `Agent   : ${d.agent_name}`,
    `Score   : ${pct}/100`,
    `Tier    : ${scoreToTier(pct)}`,
    `Date    : ${new Date().toISOString()}`,
    "",
    "Controls:",
    rows,
    "",
    "Generated by ACP-SEC",
  ].join("\n");
}

function downloadReport(d: ScoreData): void {
  const url = URL.createObjectURL(
    new Blob([buildReportText(d)], { type: "text/plain" }),
  );
  const a = Object.assign(document.createElement("a"), {
    href: url,
    download: `acp-sec-audit-${Date.now()}.txt`,
  });
  a.click();
  URL.revokeObjectURL(url);
}

export function DashboardView() {
  const score = useScore();
  useControls(); // preload the catalogue (fire-and-forget)

  const scoreData = useDashboardStore((s) => s.scoreData);
  const source = useDashboardStore((s) => s.source);
  const cachedAt = useDashboardStore((s) => s.cachedAt);
  const setScoreData = useDashboardStore((s) => s.setScoreData);
  const setSource = useDashboardStore((s) => s.setSource);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Load precedence (confirmed): a fresh handoff (<1h) wins so the leaderboard
  // drill-down displays the clicked agent; otherwise the server session score;
  // otherwise the empty state. `decided` locks the choice once made.
  const decided = useRef(false);
  useEffect(() => {
    if (decided.current) return;

    const handoff = readHandoff();
    if (handoff) {
      decided.current = true;
      setScoreData(handoff.data);
      setSource("handoff", handoff.ts);
      return;
    }
    if (score.data?.ok) {
      decided.current = true;
      setScoreData(score.data.data);
      setSource("session");
    }
  }, [score.data, setScoreData, setSource]);

  // Refresh: refetch the server score and apply it (source 'session'), mirroring
  // the lama's fetchFromAPI. If the server has no score, the current view stays.
  async function handleRefresh() {
    const res = await score.refetch();
    if (res.data?.ok) {
      setScoreData(res.data.data);
      setSource("session");
    }
  }

  function handleExport() {
    if (scoreData) downloadReport(scoreData);
  }

  const loading = score.isLoading && !scoreData;
  const errored = score.isError && !scoreData;

  return (
    <div className="mx-auto max-w-6xl px-6 py-section">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-heading font-extrabold tracking-tight">Dashboard</h1>
          <p className="mt-1 text-caption text-fg-muted">
            Agent Commerce Security Audit
          </p>
        </div>
        <HeaderActions
          onLoadReport={() => fileInputRef.current?.click()}
          onRefresh={handleRefresh}
          onExport={handleExport}
          refreshing={score.isFetching}
          exportDisabled={!scoreData}
        />
      </div>

      <div className="mt-6">
        {loading ? (
          <p className="rounded-lg border border-border bg-surface px-4 py-8 text-center text-caption text-fg-muted">
            Loading…
          </p>
        ) : errored ? (
          <p className="rounded-lg border border-border bg-surface px-4 py-8 text-center text-caption text-danger">
            Could not load score — {score.error?.message}
          </p>
        ) : (
          <>
            <ScoreSummary
              scoreData={scoreData}
              source={source}
              cachedAt={cachedAt}
            />
            {scoreData && <ScoreChart controls={scoreData.controls} />}
            {scoreData && <ControlsGrid controls={scoreData.controls} />}
          </>
        )}
      </div>

      <LoadReportDropzone inputRef={fileInputRef} />
    </div>
  );
}
